### ISSUE TITLE
invalid markup inside <noscript>-Tag

### ISSUE THREAD

**Issue by tomtom-berlin** [kaystrobach/TYPO3.piwik#10]
Hi,

the *<noscript>*-Tag ends up with invalid markup because the ampersand sign of the src attribute of the tracking pixel isn't masked as entity. I did a little change to footer.php as a workaround (line numbers 131-135:

    131    if (strlen($this->piwikOptions['trackGoal'])) {
    132       $template = str_replace('###TRACKING_IMAGE_URL###', str_replace('&','&amp;', $this->piwikTracker->getUrlTrackGoal($this->piwikOptions['trackGoal'])), $template);
    133    } else {
    134        $template = str_replace('###TRACKING_IMAGE_URL###', str_replace('&','&amp;', $this->piwikTracker->getUrlTrackPageView()), $template);
    135    }

The second ```str_replace(...)``` instruction does the trick.
HTH
Thomas.

**Comment by kaystrobach** [comment]
@tomtom-berlin could you please use urlencode and do a Merge Request, IMHO you should be able to do the pull request via the webUI as well. Thx

**Comment by tomtom-berlin** [comment]
Hey,

urlencode at that place will not work because it masks all characters, including slashes and question marks a.s.o. of url scheme and hostname. 
%2F%2Fmyhost.tld%sFpiwik.php%3F... doesn’t look so well :) To get that I have to dive deeper into the project, but I’m just out of time to do more than my workaround.

I’m not so familiar with git, but i will do my very best tonight. I did not check out the extension yet but load it via TYPO3 extension manager. While I am testing my new web project the w3 validator throws a few errors inside the <noscript> tag of the piwik extension, though I fumbled around for a solution…
But yes, I will check it out this evening and merge it back, if you didn’t mind.

Greetings, Thomas.

**Comment by kaystrobach** [comment]
yeah, sry  i meant ```htmlspecialchars``` that's what can happen if you type on mobile ... sry

**Comment by tomtom-berlin** [comment]
could not merge or sync it because of insufficient permissions. 
Greetings, Thomas.

**Comment by kaystrobach** [comment]
see here for more information, normally all repos are write protected ... it's about security.

Please create a pull request 

https://help.github.com/articles/using-pull-requests/

**Comment by tomtom-berlin** [comment]
Hello,

I hope to get it right now, made a pull request 5 minutes ago... As said, I'm not very familiar with git/github.

Another question: does your extension respect the DNT-header? I tried with both settings, on and off, and in both cases the tracking code is inserted into the site markup before the closing <body>-Tag. Shouldn't there be a notice like 'Not tracked because of active DNT-header' or similar, as it is when I'm logged in as a backend-user? 

Greetings, Thomas.

**Comment by kaystrobach** [comment]
thank you pull request is merged now!

The DNT header is not respected by the extension itself, but should be by your piwik integration.

Reason is easy, adding another TYPO3Script condition will pollute you caching tables even more so i tried to avoid that and prefer to use the stuff shipped with piwik.
