### ISSUE TITLE
Merge features from fork

### ISSUE THREAD

**Issue by astehlik** [kaystrobach/TYPO3.piwik#3]
Hi Kay,

we developed some enhancements for the piwik extension in the past. Please feel free to merge the features from:

https://github.com/Intera/typo3-extension-piwik

The changes are already rebased on the latest version of your repository.

Please let me know if we can help.

Cheers,
Alex

**Comment by kaystrobach** [comment]
@astehlik you could have created a merge request directly ;) anyway i did now, will check lateron if i can easily merge it, atleast the composer.json is a problem, but this is a rather small one

thanks for sharing.

**Comment by astehlik** [comment]
Thanks for the quick feedback :)

I have created a pull request without the composer.json commit:

https://github.com/kaystrobach/TYPO3.piwik/pull/5

**Comment by kaystrobach** [comment]
thank you!

will do review and then merge, but have to do some other stuff now

**Comment by kaystrobach** [comment]
should be merged now, so i close the issue

**Comment by astehlik** [comment]
Thank you for cleaning up the issues (also in forge) :)

**Comment by kaystrobach** [comment]
feel free to reopen if i closed one accidently, piwikintegration is also working with latest piwik again ...

**Comment by astehlik** [comment]
Yes, this is really great. Had some issues lately with an older Piwik version and needed to upgrade.

Unfortunatly I need to run in in TYPO3 4.5, this is why i created a backport branch:

**Comment by kaystrobach** [comment]
ok, 4.5 is out of my scope from now on ;) but good to see that ;) perhaps i can import that branch as well ... let me think about it

**Comment by astehlik** [comment]
Your're doing right. 4.5 should die, the sooner the better. I hope I can upgrade that instance soon so that I can just use the current master.

**Comment by kaystrobach** [comment]
:+1:
