### ISSUE TITLE
Make it (feel) compatible to TYPO3 v6.2

### ISSUE THREAD

**Issue by kboss** [kaystrobach/TYPO3.piwik#6]
Right now ext_emconf.php states compatibility wirth TYPO3 CMS 4.5.0-6.0.99 

This is a bit annoying on 6.2 LTS instances, as the extension seems to work nicely... :-)

**Comment by kboss** [comment]
Ouh, works only almost nicely...
I just discovered that the surpression of the tracking code when you're logged in as BEUser is not working.

**Comment by kaystrobach** [comment]
have you tried the git master? it should work even better, and is marked as 6.2 compat, but due to lack of feedback i have not yet released it ...

**Comment by kboss** [comment]
Cool, i'll give it a try and will return with some feedback!

**Comment by kaystrobach** [comment]
close due to lack of feedback ... feel free to reopen if there are issues with current master
