### ISSUE TITLE
trackBackendUsers = 0 doesnt work in multidomain environments

### ISSUE THREAD

**Issue by kboss** [kaystrobach/TYPO3.piwik#8]
Right now `trackBackendUsers = 0` does only work within the same domain you are logged in to the backend. 

Is there a possibility to enhance this functionality that it would work for a page tree serving multiple domains?

**Comment by kaystrobach** [comment]
automatically no.

But:
* you can use the optout functionality of piwik for each domain
* if you have static IPs most time, you can remove the tracking code by IP via some TS conditions
